const labels = {
  name: "Name :",
  last_name: "Last Name :",
  email: "Email :",
  Titel_blog: "Title Of Blog :",
  phone: "Enter You Phone No :",
  about: "Write About :",
  fav_author: "Favorite Author :",
  address: "Address :",
  father_name: "Father Name :",
  mother_name: "Mother Name :",
  Accountno: "Account No :",
  Drive_link: "Drive Link :",
  Date_d :"Enter Date :",
  password: "Password :",
  account: "Account No :",
  drivelink: "Drive Link :",
  your_name:"Hi Welcome ",
  your_last_name:"This Is Your Last_name :",
  your_email:"Email :",
  your_phone:"Phone NO :",
  your_about:"About :",
  your_blog_titel:"Blog Title :",
  your_fav_author:"Favorite Author :",
  your_father_name:"Father Name :",
  your_mother_name:"Mother name :",
  your_address:"Address :",
  Your_data:"Date :",
};
export default labels;